codecov: 
 token: 8f08768a-0629-4ed0-91b9-bdd9f7019916

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
